use serde::{Deserialize, Serialize};
use strum::Display;

#[derive(Debug, Clone, PartialEq, Eq, Display, Serialize, Deserialize)]
pub enum Action {
    Tick,
    Render,
    Resize(u16, u16),
    Suspend,
    Resume,
    Quit,
    ClearScreen,
    Error(String),
    Help,

    SelectTableMode,
    SelectTablePrev,
    SelectTableNext,
    SelectTableScrollUp,
    SelectTableScrollDown,
    SelectTableFirst,
    SelectTableLast,
    SelectTable,
    TransmitSelectedTable(String),

    SelectDataMode,
    SelectTableDataRowPrev,
    SelectTableDataRowNext,
    SelectTableDataRowScrollUp,
    SelectTableDataRowScrollDown,
    SelectTableDataRowFirst,
    SelectTableDataRowLast,
    SelectTableDataRow,
    TransmitTableData(Vec<String>, bool),
    TransmitNextBatcTableData(Vec<String>, bool),
    FetchTableData(String),
    FetchMoreTableData(String),
    LoadMoreTableData(String),

    FilteringTables,
    SelectingRegion,
    EnterInsertMode,
    ExitInsertMode,
    NewCharacter(char),
    DeleteCharacter,
    SubmitText,
    TransmitSubmittedText(String),
    FetchTables,
    TransmitTables(Vec<String>),
    StartLoading(String),
    StopLoading,
}
